library:
  source-dirs: src
tests:
  HengenPixel-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HengenPixel
copyright: 2019 cuboktahedron
maintainer: cuboktahedron@gmail.com
dependencies:
- mtl
- parsec
- base >= 4.7 && < 5
name: HengenPixel
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: cuboktahedron
github: cuboktahedron/HengenPixel
license: BSD3
executables:
  HengenPixel-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HengenPixel
description: Please see the README on GitHub at <https://github.com/cuboktahedron/HengenPixel#readme>
